In [1]:
import pandas as pd

In [2]:
oil = pd.read_csv('Oil.csv')

In [3]:
oil

,Date,Open,High,Low,Close,Adj Close,Volume
0,11/4/2016,39.720001,40.750000,39.250000,40.360001,40.360001,679351.0
1,12/4/2016,40.349998,42.250000,40.090000,42.169998,42.169998,796837.0
2,13/4/2016,41.630001,42.419998,41.240002,41.759998,41.759998,730437.0
3,14/4/2016,41.540001,42.160000,40.840000,41.500000,41.500000,488614.0
4,15/4/2016,41.430000,41.730000,39.980000,40.360001,40.360001,520146.0
...,...,...,...,...,...,...,...
1252,2/4/2021,61.450001,61.450001,61.450001,61.450001,61.450001,605567.0
1253,5/4/2021,61.500000,61.500000,57.630001,58.650002,58.650002,438864.0
1254,6/4/2021,58.799999,60.900002,58.619999,59.330002,59.330002,457348.0
1255,7/4/2021,59.259998,60.040001,58.119999,59.770000,59.770000,475537.0
1256,8/4/2021,59.520000,59.930000,58.820000,59.599998,59.599998,475537.0

In [4]:
oil.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume       float64
dtype: object

In [6]:
oil = pd.read_csv('Oil.csv', index_col='Date')

# oil = pd.read_csv('Oil.csv')
# oil = oil.set_index('Date')

In [7]:
# oil_xlsx = pd.read_excel('Oil.xlsx')
# oil_xlsx = pd.read_excel('Oil.xlsx' sheet_name=['CVX'])

In [8]:
# oil_xlsx['Oil']
# oil_xlsx['CVX']

In [9]:
import pandas_datareader as web

start = '2020-01-01'
end = '2021-01-01'

In [10]:
tsla = web.get_data_yahoo('TSLA', start=start, end=end)
tsla

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2019-12-31,84.258003,80.416000,81.000000,83.666000,51428500.0,83.666000
2020-01-02,86.139999,84.342003,84.900002,86.052002,47660500.0,86.052002
2020-01-03,90.800003,87.384003,88.099998,88.601997,88892500.0,88.601997
2020-01-06,90.311996,88.000000,88.094002,90.307999,50665000.0,90.307999
2020-01-07,94.325996,90.671997,92.279999,93.811996,89410500.0,93.811996
...,...,...,...,...,...,...
2020-12-24,666.090027,641.000000,642.989990,661.770020,22865600.0,661.770020
2020-12-28,681.400024,660.799988,674.510010,663.690002,32278600.0,663.690002
2020-12-29,669.900024,655.000000,661.000000,665.989990,22910800.0,665.989990
2020-12-30,696.599976,668.359985,672.000000,694.780029,42846000.0,694.780029
2020-12-31,718.719971,691.119995,699.989990,705.669983,49649900.0,705.669983

In [11]:
tsla_weekly = tsla.asfreq('W-Mon')
tsla_weekly

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-01-06,90.311996,88.000000,88.094002,90.307999,50665000.0,90.307999
2020-01-13,105.125999,98.400002,98.699997,104.972000,132588000.0,104.972000
2020-01-20,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-27,112.888000,107.856003,108.398003,111.603996,68040500.0,111.603996
2020-02-03,157.227997,134.703995,134.738007,156.000000,235325000.0,156.000000
2020-02-10,163.998001,150.479996,160.000000,154.255997,123446000.0,154.255997
2020-02-17,NaN,NaN,NaN,NaN,NaN,NaN
2020-02-24,172.699997,164.440002,167.800003,166.757996,75961000.0,166.757996
2020-03-02,148.738007,137.334000,142.251999,148.723999,100975000.0,148.723999
2020-03-09,132.600006,121.000000,121.078003,121.599998,85368500.0,121.599998
2020-03-16,98.973999,88.433998,93.900002,89.014000,102447500.0,89.014000
2020-03-23,88.400002,82.099998,86.720001,86.858002,82272500.0,86.858002
2020-03-30,103.330002,98.246002,102.052002,100.426003,59990500.0,100.426003
2020-04-06,104.199997,99.592003,102.239998,103.248001,74509000.0,103.248001
2020-04-13,130.399994,116.106003,118.031998,130.190002,112377000.0,130.190002
2020-04-20,153.113998,142.442001,146.539993,149.272003,73733000.0,149.272003
2020-04-27,159.897995,147.000000,147.522003,159.750000,103407000.0,159.750000
2020-05-04,152.399994,139.600006,140.199997,152.238007,96185500.0,152.238007
2020-05-11,164.800003,157.000000,158.102005,162.257996,82598000.0,162.257996
2020-05-18,166.944000,160.776001,165.556000,162.725998,58329000.0,162.725998
2020-05-25,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-01,179.800003,170.820007,171.600006,179.619995,74697500.0,179.619995
2020-06-08,190.000000,181.832001,183.800003,189.983994,70873500.0,189.983994
2020-06-15,199.768005,181.699997,183.557999,198.179993,78486000.0,198.179993
2020-06-22,201.776001,198.003998,199.990005,198.863998,31812000.0,198.863998
2020-06-29,202.000000,189.703995,193.802002,201.869995,45132000.0,201.869995
2020-07-06,275.558014,253.207993,255.337997,274.316010,102849500.0,274.316010
2020-07-13,358.997986,294.221985,331.799988,299.411987,194927000.0,299.411987
2020-07-20,330.000000,297.600006,303.802002,328.600006,85607000.0,328.600006
2020-07-27,309.588013,282.600006,287.000000,307.920013,80243500.0,307.920013
2020-08-03,301.962006,288.876007,289.839996,297.000000,44046500.0,297.000000
2020-08-10,291.500000,277.167999,289.600006,283.713989,37611500.0,283.713989
2020-08-17,369.171997,334.566010,335.399994,367.127991,101211500.0,367.127991
2020-08-24,425.799988,385.503998,425.256012,402.839996,100318000.0,402.839996
2020-08-31,500.140015,440.109985,444.609985,498.320007,118374400.0,498.320007
2020-09-07,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-14,420.000000,373.299988,380.950012,419.619995,83020600.0,419.619995
2020-09-21,455.679993,407.070007,453.130005,449.390015,109476800.0,449.390015
2020-09-28,428.079987,415.549988,424.619995,421.200012,49719600.0,421.200012
2020-10-05,433.640015,419.329987,423.350006,425.679993,44722800.0,425.679993
2020-10-12,448.739990,438.579987,442.000000,442.299988,38791100.0,442.299988
2020-10-19,447.000000,428.869995,446.239990,430.829987,36287800.0,430.829987
2020-10-26,425.760010,410.000000,411.630005,420.279999,28239200.0,420.279999
2020-11-02,406.980011,392.299988,394.000000,400.510010,29021100.0,400.510010
2020-11-09,452.500000,421.000000,439.500000,421.260010,34833000.0,421.260010
2020-11-16,412.450012,404.089996,408.929993,408.089996,26838600.0,408.089996
2020-11-23,526.000000,501.790009,503.500000,521.849976,50260300.0,521.849976
2020-11-30,607.799988,554.510010,602.210022,567.599976,63003100.0,567.599976
2020-12-07,648.789978,603.049988,604.919983,641.760010,56309700.0,641.760010
2020-12-14,642.750000,610.200012,619.000000,639.830017,52040600.0,639.830017
2020-12-21,668.500000,646.070007,666.239990,649.859985,58045300.0,649.859985
2020-12-28,681.400024,660.799988,674.510010,663.690002,32278600.0,663.690002

In [12]:
tsla_monthly = tsla.resample('M').mean()
tsla_monthly

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2019-12-31,84.258003,80.416000,81.000000,83.666000,5.142850e+07,83.666000
2020-01-31,107.285715,102.938000,104.609048,105.731809,9.695679e+07,105.731809
2020-02-29,166.152104,153.288210,158.950842,159.489368,1.243649e+08,159.489368
2020-03-31,117.411547,106.974091,112.785091,111.820273,9.566705e+07,111.820273
2020-04-30,137.320382,128.212762,133.058952,132.719715,9.082798e+07,132.719715
2020-05-31,163.147200,156.069100,159.812000,159.885102,6.817590e+07,159.885102
2020-06-30,196.173181,187.734000,191.638728,192.708453,5.813016e+07,192.708453
2020-07-31,303.024820,281.311821,292.988002,292.028179,8.605307e+07,292.028179
2020-08-31,367.357906,346.349333,354.512284,360.059711,7.416088e+07,360.059711
2020-09-30,428.257618,395.665713,414.282859,413.495239,8.268023e+07,413.495239
2020-10-31,436.831822,421.228180,430.490458,427.209545,3.789393e+07,427.209545
2020-11-30,476.083501,453.335501,464.273001,465.612498,3.912994e+07,465.612498
2020-12-31,647.822726,615.457725,631.504095,638.818640,5.437936e+07,638.818640

In [14]:
import quandl

In [15]:
quandl.ApiConfig.api_key = 'API_Keys'

In [16]:
msft = quandl.get('EOD/MSFT', start_date=start, end_date=end)
msft

AuthenticationError: (Status 400) (Quandl Error QEAx01) We could not recognize your API key: API_Keys. Please check your API key and try again. You can find your API key under your account settings.

In [17]:
data = quandl.get_table('WIKI/PRICES', ticker = ['AAPL'],
                        qopts = {'columns' : ['ticker', 'date', 'adj_close']},
                        data = {'gte' : '2016-01-01', 'lte' : '2021-01-01'},
                        paginate = True)
data

InvalidRequestError: (Status 422) (Quandl Error QESx08) You cannot use data column as a filter.

In [ ]:
df = data.iloc[::-1]
df

In [18]:
import yfinance as yf
tickerSymbol = 'NFLX'

In [ ]:
tickerData = yf.Ticker(tickerSymbol)
tickerDf = tickerData.history(period='1d', start=start, end=end)
tickerDf

In [ ]:
tickerData.calendar

In [ ]:
tickerData.recommendations

In [19]:
from google.colab import drive
drive.mount('/content/drive')
# follow the url then get auth code

ModuleNotFoundError: No module named 'google'

In [ ]:
df = pd.read_csv(path) # path from google drive